package com.bot;
public enum UserState {
    SELECTING_GENDER,
    SELECTING_RATING_TYPE,
    WAITING_FOR_PHOTO,
    WAITING_FOR_MEASUREMENTS,
    WAITING_FOR_HEIGHT,
    WAITING_FOR_WEIGHT,
    WAITING_FOR_CHEST,
    WAITING_FOR_WAIST,
    WAITING_FOR_HIPS,
    WAITING_FOR_SHOULDERS,
    WAITING_FOR_NECK,
    WAITING_FOR_RECEIPT
}
